#!/bin/bash

if [[ "$1" == "--configure" ]]; then
  echo "Running startscript with --configure option"
else
  echo "ERROR: Unknown command line option(s): '$@'"
  exit 10
fi

mkdir /www
cd www

echo '<html><head><title>HTTP Hello World</title></head><body><h1>Hello from </h1></body></html' > index.html

python3 -m http.server 80 &
