name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create app config 02
        run: chmod +x appconfig/startscript; tar cvzf ../02-config-package-appconfig.tgz appconfig
        working-directory: ./02-config-package/
      - name: Create app config 03
        run: chmod +x appconfig/startscript; tar cvzf ../03-centos-ad-ldap-appconfig.tgz appconfig
        working-directory: ./03-centos-ad-ldap/
      - name: Delete old release assets
        id: delete_release
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 0
          delete_tag_pattern: release # defaults to ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release
          release_name: release
          draft: false
          prerelease: false

      - name: Upload Release Asset 02
        id: upload-release-asset-02
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object,
          # which include a `upload_url`. See this blog post for more info:
          # https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./02-config-package-appconfig.tgz
          asset_name: 02-config-package-appconfig.tgz
          asset_content_type: application/gzip
          
  
      - name: Upload Release Asset 03
        id: upload-release-asset-03
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object,
          # which include a `upload_url`. See this blog post for more info:
          # https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./03-centos-ad-ldap-appconfig.tgz
          asset_name: 03-centos-ad-ldap-appconfig.tgz
          asset_content_type: application/gzip
